#!/usr/bin/env python
from setup_utils import *
import os

# authn.ldap
def undeploy():
    app = actions.getAppName("authn_ldap.ear")
    if app: actions.undeploy(app) 
    app = actions.getAppName("authn_ldap")
    if app: actions.undeploy(app)
    app = actions.getAppName("authn.ldap")
    if app: actions.undeploy(app)

actions, arg, props = getActions("authn_ldap-setup.properties", [])

prop_name = "authn_ldap.properties"
prop_list = []

if arg in ["CONFIGURE", "INSTALL"]:
    actions.configure(prop_name, prop_list)
    actions.checkNoErrors()
    
if arg == "INSTALL":
    getProperties(prop_name, prop_list)              
    actions.installFile(prop_name)
    
    try:
        undeploy()
        actions.deploy(deploymentorder=80)  
        app = actions.getAppName("icat.server")
        if app: actions.restartApp(app)
    except Exception, e:
        abort(str(e))
               
if arg == "UNINSTALL":
    actions.removeFile(prop_name)
    try:
        undeploy()
    except Exception, e:
        abort(str(e))       
    
            
    
